before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - ldflags:
      - -s -w -X "github.com/yankeexe/air-quality-cli/cmd.Version={{.Tag}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
